name: path_provider_macos
description: macOS implementation of the path_provider plugin
repository: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: path_provider
    platforms:
      macos:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderMacOS

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path_provider_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.0
  pedantic: ^1.10.0
